/**
 * Flota.
 *
 * Se define un catálogo de modelos y los puertos donde opera cada uno; la
 * semilla cruza ambas cosas y genera un barco por combinación. Los consumos
 * son los reales de cada casco: son la mitad del argumento del producto, así
 * que inventarlos a la baja sería tirar piedras contra el propio tejado.
 */

export interface ModeloSemilla {
  nombre: string;
  fabricante: string;
  modelo: string;
  anio: number;
  tipo: string;
  descripcion: string;
  esloraCm: number;
  capacidad: number;
  camarotes: number;
  aseos: number;
  potenciaCv: number;
  /** Tarifa base diaria en céntimos, antes del factor del destino. */
  precioBaseDia: number;
  limpieza: number;
  tasaPortuariaDia: number;
  patronDia: number | null;
  fianza: number;
  consumoLitrosHora: number;
  descuentoSemana: number;
  requiereTitulacion: boolean;
  minimoDias: number;
  equipamiento: string[];
  experiencias: string[];
  puertos: string[];
}

/**
 * Lo que cuesta el mismo casco según dónde se amarre. Ibiza y Formentera
 * pagan la prima del destino; el Mar Menor y la costa de Alicante son los
 * sitios donde el dinero cunde más.
 */
export const FACTOR_DESTINO: Record<string, number> = {
  denia: 0.85,
  javea: 0.95,
  moraira: 0.95,
  calpe: 0.9,
  altea: 0.9,
  benidorm: 0.9,
  villajoyosa: 0.8,
  alicante: 0.85,
  "el-campello": 0.8,
  torrevieja: 0.8,
};

export const MODELOS: ModeloSemilla[] = [
  // ---------------------------------------------------------------- neumáticas
  {
    nombre: "Nuova Jolly 470",
    fabricante: "Nuova Jolly",
    modelo: "King 470",
    anio: 2022,
    tipo: "neumatica",
    descripcion:
      "Semirrígida de 4,7 metros con motor de 15 caballos: la máxima potencia que se puede gobernar sin ningún título. Entra en calas donde no cabe nada más y se maneja en diez minutos de explicación en el pantalán.",
    esloraCm: 470,
    capacidad: 5,
    camarotes: 0,
    aseos: 0,
    potenciaCv: 15,
    precioBaseDia: 13_000,
    limpieza: 3_000,
    tasaPortuariaDia: 2_000,
    patronDia: null,
    fianza: 50_000,
    consumoLitrosHora: 6,
    descuentoSemana: 10,
    requiereTitulacion: false,
    minimoDias: 1,
    equipamiento: ["gps", "sonda", "nevera", "bimini", "snorkel", "chalecos"],
    experiencias: ["calas-y-snorkel"],
    puertos: ["marina-denia", "santa-pola", "xabia", "les-bassetes", "benidorm", "villajoyosa"],
  },
  {
    nombre: "Zodiac Open 5.5",
    fabricante: "Zodiac",
    modelo: "Open 5.5",
    anio: 2021,
    tipo: "neumatica",
    descripcion:
      "Semirrígida de 5,5 metros y 100 caballos, rápida y seca con mar formada. Para grupos pequeños que quieren cubrir distancia sin el consumo de una lancha grande.",
    esloraCm: 550,
    capacidad: 8,
    camarotes: 0,
    aseos: 0,
    potenciaCv: 100,
    precioBaseDia: 22_000,
    limpieza: 4_000,
    tasaPortuariaDia: 2_500,
    patronDia: 16_000,
    fianza: 80_000,
    consumoLitrosHora: 18,
    descuentoSemana: 10,
    requiereTitulacion: true,
    minimoDias: 1,
    equipamiento: ["gps", "sonda", "radio-vhf", "nevera", "bimini", "snorkel", "chalecos"],
    experiencias: ["calas-y-snorkel", "atardecer"],
    puertos: ["marina-denia", "el-campello", "moraira", "altea", "villajoyosa", "marina-internacional"],
  },

  // -------------------------------------------------------------------- lanchas
  {
    nombre: "Quicksilver Activ 675",
    fabricante: "Quicksilver",
    modelo: "Activ 675 Open",
    anio: 2023,
    tipo: "lancha",
    descripcion:
      "La lancha de día más equilibrada del mercado: 6,75 metros, 200 caballos, solárium de proa y plataforma de baño. Suficiente para ocho personas sin que nadie vaya incómodo.",
    esloraCm: 675,
    capacidad: 8,
    camarotes: 0,
    aseos: 1,
    potenciaCv: 200,
    precioBaseDia: 30_000,
    limpieza: 8_000,
    tasaPortuariaDia: 4_500,
    patronDia: 18_000,
    fianza: 100_000,
    consumoLitrosHora: 35,
    descuentoSemana: 15,
    requiereTitulacion: true,
    minimoDias: 1,
    equipamiento: [
      "gps",
      "sonda",
      "radio-vhf",
      "nevera",
      "ducha-popa",
      "bimini",
      "altavoz",
      "plataforma-bano",
      "snorkel",
      "chalecos",
    ],
    experiencias: ["calas-y-snorkel", "atardecer"],
    puertos: ["marina-denia", "calpe", "campomanes", "marina-internacional", "rcn-torrevieja"],
  },
  {
    nombre: "Jeanneau Cap Camarat 7.5",
    fabricante: "Jeanneau",
    modelo: "Cap Camarat 7.5 WA",
    anio: 2022,
    tipo: "lancha",
    descripcion:
      "Walkaround de 7,5 metros con camarote de proa para cambiarse y guardar el equipo. Casco muy marinero: aguanta bien la mar corta de la tarde cuando entra el térmico.",
    esloraCm: 750,
    capacidad: 9,
    camarotes: 1,
    aseos: 1,
    potenciaCv: 225,
    precioBaseDia: 36_000,
    limpieza: 9_000,
    tasaPortuariaDia: 5_000,
    patronDia: 18_000,
    fianza: 120_000,
    consumoLitrosHora: 40,
    descuentoSemana: 15,
    requiereTitulacion: true,
    minimoDias: 1,
    equipamiento: [
      "gps",
      "sonda",
      "radio-vhf",
      "nevera",
      "ducha-popa",
      "bimini",
      "altavoz",
      "plataforma-bano",
      "cana-pesca",
      "chalecos",
    ],
    experiencias: ["calas-y-snorkel", "pesca", "atardecer"],
    puertos: ["xabia", "les-bassetes", "rcn-torrevieja", "benidorm"],
  },
  {
    nombre: "Beneteau Flyer 8",
    fabricante: "Bénéteau",
    modelo: "Flyer 8 SUNdeck",
    anio: 2023,
    tipo: "lancha",
    descripcion:
      "Ocho metros de motora con la cubierta más aprovechada de su clase. Dos solárium, mesa de popa y 250 caballos: llega a cualquier cala de la isla en menos de una hora.",
    esloraCm: 800,
    capacidad: 10,
    camarotes: 1,
    aseos: 1,
    potenciaCv: 250,
    precioBaseDia: 44_000,
    limpieza: 10_000,
    tasaPortuariaDia: 6_000,
    patronDia: 20_000,
    fianza: 150_000,
    consumoLitrosHora: 45,
    descuentoSemana: 15,
    requiereTitulacion: true,
    minimoDias: 1,
    equipamiento: [
      "gps",
      "piloto-automatico",
      "sonda",
      "radio-vhf",
      "nevera",
      "ducha-popa",
      "cocina",
      "bimini",
      "altavoz",
      "plataforma-bano",
      "chalecos",
    ],
    experiencias: ["calas-y-snorkel", "atardecer", "celebraciones"],
    puertos: ["marina-alicante", "el-campello", "altea", "moraira", "benidorm", "villajoyosa"],
  },

  // -------------------------------------------------------------------- veleros
  {
    nombre: "Bénéteau Oceanis 38.1",
    fabricante: "Bénéteau",
    modelo: "Oceanis 38.1",
    anio: 2021,
    tipo: "velero",
    descripcion:
      "Crucero de 11,6 metros con tres camarotes, pensado para travesías de una semana. Aparejo sencillo de llevar entre dos personas y un consumo casi anecdótico: el motor solo entra para maniobrar.",
    esloraCm: 1_160,
    capacidad: 8,
    camarotes: 3,
    aseos: 2,
    potenciaCv: 30,
    precioBaseDia: 32_000,
    limpieza: 12_000,
    tasaPortuariaDia: 6_500,
    patronDia: 22_000,
    fianza: 200_000,
    consumoLitrosHora: 4,
    descuentoSemana: 20,
    requiereTitulacion: true,
    minimoDias: 3,
    equipamiento: [
      "gps",
      "piloto-automatico",
      "sonda",
      "radio-vhf",
      "nevera",
      "cocina",
      "ducha-popa",
      "bimini",
      "snorkel",
      "chalecos",
      "balsa",
    ],
    experiencias: ["calas-y-snorkel", "atardecer"],
    puertos: ["santa-pola", "marina-denia", "campomanes", "calpe", "villajoyosa", "marina-internacional"],
  },
  {
    nombre: "Jeanneau Sun Odyssey 419",
    fabricante: "Jeanneau",
    modelo: "Sun Odyssey 419",
    anio: 2020,
    tipo: "velero",
    descripcion:
      "Doce metros y setenta de eslora con bañera de doble timón y acceso directo a la plataforma de baño. Tres camarotes dobles y una mesa de carta de verdad para planificar la travesía.",
    esloraCm: 1_270,
    capacidad: 8,
    camarotes: 3,
    aseos: 2,
    potenciaCv: 45,
    precioBaseDia: 38_000,
    limpieza: 13_000,
    tasaPortuariaDia: 7_000,
    patronDia: 22_000,
    fianza: 220_000,
    consumoLitrosHora: 4.5,
    descuentoSemana: 20,
    requiereTitulacion: true,
    minimoDias: 3,
    equipamiento: [
      "gps",
      "piloto-automatico",
      "sonda",
      "radio-vhf",
      "nevera",
      "cocina",
      "ducha-popa",
      "bimini",
      "paddle-surf",
      "snorkel",
      "chalecos",
      "balsa",
    ],
    experiencias: ["calas-y-snorkel"],
    puertos: ["marina-alicante", "xabia", "les-bassetes", "marina-internacional", "rcn-torrevieja"],
  },
  {
    nombre: "Bavaria Cruiser 46",
    fabricante: "Bavaria",
    modelo: "Cruiser 46",
    anio: 2019,
    tipo: "velero",
    descripcion:
      "Catorce metros y cuatro camarotes dobles: el velero de flotilla por excelencia. Espacio de sobra para diez personas en travesía de una semana por Baleares.",
    esloraCm: 1_425,
    capacidad: 10,
    camarotes: 4,
    aseos: 2,
    potenciaCv: 55,
    precioBaseDia: 48_000,
    limpieza: 15_000,
    tasaPortuariaDia: 8_500,
    patronDia: 24_000,
    fianza: 300_000,
    consumoLitrosHora: 5,
    descuentoSemana: 22,
    requiereTitulacion: true,
    minimoDias: 5,
    equipamiento: [
      "gps",
      "piloto-automatico",
      "sonda",
      "radio-vhf",
      "nevera",
      "cocina",
      "ducha-popa",
      "aire-acondicionado",
      "bimini",
      "paddle-surf",
      "snorkel",
      "chalecos",
      "balsa",
    ],
    experiencias: ["calas-y-snorkel", "celebraciones"],
    puertos: ["el-campello", "xabia", "moraira", "altea", "rcn-torrevieja", "benidorm"],
  },
  {
    nombre: "Dufour 390 Grand Large",
    fabricante: "Dufour",
    modelo: "390 Grand Large",
    anio: 2022,
    tipo: "velero",
    descripcion:
      "Doce metros con una bañera enorme y cocina en L. Barco noble bajo vela, cómodo de llevar y con muy buen comportamiento en la mar de la tramontana.",
    esloraCm: 1_199,
    capacidad: 8,
    camarotes: 3,
    aseos: 2,
    potenciaCv: 40,
    precioBaseDia: 36_000,
    limpieza: 13_000,
    tasaPortuariaDia: 7_000,
    patronDia: 22_000,
    fianza: 200_000,
    consumoLitrosHora: 4.2,
    descuentoSemana: 20,
    requiereTitulacion: true,
    minimoDias: 3,
    equipamiento: [
      "gps",
      "piloto-automatico",
      "sonda",
      "radio-vhf",
      "nevera",
      "cocina",
      "ducha-popa",
      "bimini",
      "snorkel",
      "chalecos",
      "balsa",
    ],
    experiencias: ["calas-y-snorkel", "atardecer"],
    puertos: ["marina-denia", "marina-alicante", "calpe", "campomanes", "benidorm", "villajoyosa"],
  },

  // ---------------------------------------------------------------- catamaranes
  {
    nombre: "Lagoon 42",
    fabricante: "Lagoon",
    modelo: "Lagoon 42",
    anio: 2021,
    tipo: "catamaran",
    descripcion:
      "El catamarán más alquilado del Mediterráneo. Cuatro camarotes dobles, flybridge y una plataforma de proa donde caben ocho personas tumbadas. Fondeado no se mueve.",
    esloraCm: 1_284,
    capacidad: 12,
    camarotes: 4,
    aseos: 4,
    potenciaCv: 100,
    precioBaseDia: 95_000,
    limpieza: 25_000,
    tasaPortuariaDia: 15_000,
    patronDia: 28_000,
    fianza: 400_000,
    consumoLitrosHora: 10,
    descuentoSemana: 20,
    requiereTitulacion: true,
    minimoDias: 3,
    equipamiento: [
      "gps",
      "piloto-automatico",
      "sonda",
      "radio-vhf",
      "nevera",
      "cocina",
      "ducha-popa",
      "aire-acondicionado",
      "bimini",
      "altavoz",
      "paddle-surf",
      "snorkel",
      "plataforma-bano",
      "chalecos",
      "balsa",
    ],
    experiencias: ["calas-y-snorkel", "celebraciones", "atardecer"],
    puertos: ["xabia", "santa-pola", "les-bassetes", "villajoyosa", "marina-internacional"],
  },
  {
    nombre: "Fountaine Pajot Astrea 42",
    fabricante: "Fountaine Pajot",
    modelo: "Astrea 42",
    anio: 2022,
    tipo: "catamaran",
    descripcion:
      "Catamarán de nueva generación con más luz y más ventilación que la media. Cuatro camarotes, cocina exterior en la bañera y paneles solares que dan autonomía real al fondeo.",
    esloraCm: 1_260,
    capacidad: 12,
    camarotes: 4,
    aseos: 4,
    potenciaCv: 100,
    precioBaseDia: 98_000,
    limpieza: 25_000,
    tasaPortuariaDia: 15_000,
    patronDia: 28_000,
    fianza: 400_000,
    consumoLitrosHora: 9,
    descuentoSemana: 20,
    requiereTitulacion: true,
    minimoDias: 3,
    equipamiento: [
      "gps",
      "piloto-automatico",
      "sonda",
      "radio-vhf",
      "nevera",
      "cocina",
      "ducha-popa",
      "aire-acondicionado",
      "bimini",
      "altavoz",
      "paddle-surf",
      "snorkel",
      "plataforma-bano",
      "chalecos",
      "balsa",
    ],
    experiencias: ["calas-y-snorkel", "celebraciones"],
    puertos: ["marina-alicante", "el-campello", "altea", "moraira", "marina-internacional", "rcn-torrevieja"],
  },
  {
    nombre: "Lagoon 380",
    fabricante: "Lagoon",
    modelo: "Lagoon 380",
    anio: 2018,
    tipo: "catamaran",
    descripcion:
      "El catamarán de entrada: once metros y medio, cuatro camarotes y un precio que lo pone al alcance de dos familias. Estabilidad de catamarán sin el presupuesto de un 42 pies.",
    esloraCm: 1_155,
    capacidad: 10,
    camarotes: 4,
    aseos: 2,
    potenciaCv: 60,
    precioBaseDia: 76_000,
    limpieza: 20_000,
    tasaPortuariaDia: 13_000,
    patronDia: 26_000,
    fianza: 300_000,
    consumoLitrosHora: 8,
    descuentoSemana: 20,
    requiereTitulacion: true,
    minimoDias: 3,
    equipamiento: [
      "gps",
      "piloto-automatico",
      "sonda",
      "radio-vhf",
      "nevera",
      "cocina",
      "ducha-popa",
      "bimini",
      "altavoz",
      "snorkel",
      "plataforma-bano",
      "chalecos",
      "balsa",
    ],
    experiencias: ["calas-y-snorkel", "celebraciones"],
    puertos: ["santa-pola", "marina-denia", "campomanes", "calpe", "rcn-torrevieja", "benidorm"],
  },

  // ---------------------------------------------------------------------- yates
  {
    nombre: "Azimut 55 Flybridge",
    fabricante: "Azimut",
    modelo: "55 Flybridge",
    anio: 2020,
    tipo: "yate",
    descripcion:
      "Diecisiete metros con flybridge, tres camarotes y tripulación incluida. El consumo es lo que es: ciento cuarenta litros a la hora que aquí se enseñan desde el primer momento.",
    esloraCm: 1_700,
    capacidad: 12,
    camarotes: 3,
    aseos: 3,
    potenciaCv: 1_400,
    precioBaseDia: 280_000,
    limpieza: 45_000,
    tasaPortuariaDia: 30_000,
    patronDia: 45_000,
    fianza: 1_000_000,
    consumoLitrosHora: 140,
    descuentoSemana: 12,
    requiereTitulacion: true,
    minimoDias: 1,
    equipamiento: [
      "gps",
      "piloto-automatico",
      "sonda",
      "radio-vhf",
      "nevera",
      "cocina",
      "ducha-popa",
      "aire-acondicionado",
      "bimini",
      "altavoz",
      "paddle-surf",
      "snorkel",
      "plataforma-bano",
      "chalecos",
      "balsa",
    ],
    experiencias: ["celebraciones", "atardecer"],
    puertos: ["el-campello", "xabia", "les-bassetes", "benidorm", "villajoyosa"],
  },
  {
    nombre: "Sunseeker Predator 60",
    fabricante: "Sunseeker",
    modelo: "Predator 60",
    anio: 2019,
    tipo: "yate",
    descripcion:
      "Yate deportivo de dieciocho metros con hard top eléctrico y tres camarotes. Treinta nudos de velocidad punta y el consumo que corresponde a esa cifra.",
    esloraCm: 1_830,
    capacidad: 12,
    camarotes: 3,
    aseos: 3,
    potenciaCv: 1_800,
    precioBaseDia: 350_000,
    limpieza: 50_000,
    tasaPortuariaDia: 35_000,
    patronDia: 50_000,
    fianza: 1_200_000,
    consumoLitrosHora: 165,
    descuentoSemana: 12,
    requiereTitulacion: true,
    minimoDias: 1,
    equipamiento: [
      "gps",
      "piloto-automatico",
      "sonda",
      "radio-vhf",
      "nevera",
      "cocina",
      "ducha-popa",
      "aire-acondicionado",
      "altavoz",
      "plataforma-bano",
      "chalecos",
      "balsa",
    ],
    experiencias: ["celebraciones"],
    puertos: ["marina-denia", "marina-alicante", "moraira", "altea", "villajoyosa", "marina-internacional"],
  },

  // --------------------------------------------------------------------- llaüts
  {
    nombre: "Menorquín 45",
    fabricante: "Menorquín Yachts",
    modelo: "Menorquín 45",
    anio: 2017,
    tipo: "llaut",
    descripcion:
      "El llaüt clásico de Menorca en versión de trece metros y medio: proa lanzada, techo de madera y motor lento. No corre, y de eso se trata.",
    esloraCm: 1_350,
    capacidad: 10,
    camarotes: 2,
    aseos: 1,
    potenciaCv: 220,
    precioBaseDia: 42_000,
    limpieza: 12_000,
    tasaPortuariaDia: 7_500,
    patronDia: 22_000,
    fianza: 200_000,
    consumoLitrosHora: 14,
    descuentoSemana: 15,
    requiereTitulacion: true,
    minimoDias: 1,
    equipamiento: [
      "gps",
      "sonda",
      "radio-vhf",
      "nevera",
      "cocina",
      "ducha-popa",
      "bimini",
      "snorkel",
      "plataforma-bano",
      "chalecos",
    ],
    experiencias: ["calas-y-snorkel", "atardecer", "pesca"],
    puertos: ["xabia", "santa-pola", "calpe", "campomanes", "marina-internacional", "rcn-torrevieja"],
  },
  {
    nombre: "Copino 38",
    fabricante: "Astilleros Copino",
    modelo: "Copino 38",
    anio: 2015,
    tipo: "llaut",
    descripcion:
      "Llaüt mallorquín de once metros y medio, construido en Palma. Siete plazas, sombra de verdad y un consumo de ocho litros a la hora que permite estar todo el día fuera sin pensar en el gasóleo.",
    esloraCm: 1_150,
    capacidad: 7,
    camarotes: 1,
    aseos: 1,
    potenciaCv: 150,
    precioBaseDia: 30_000,
    limpieza: 9_000,
    tasaPortuariaDia: 6_000,
    patronDia: 20_000,
    fianza: 150_000,
    consumoLitrosHora: 8,
    descuentoSemana: 15,
    requiereTitulacion: true,
    minimoDias: 1,
    equipamiento: [
      "gps",
      "sonda",
      "radio-vhf",
      "nevera",
      "ducha-popa",
      "bimini",
      "snorkel",
      "cana-pesca",
      "chalecos",
    ],
    experiencias: ["calas-y-snorkel", "pesca", "atardecer"],
    puertos: ["marina-alicante", "el-campello", "les-bassetes", "xabia", "rcn-torrevieja", "benidorm"],
  },

  // ------------------------------------------------------------- casas flotantes
  {
    nombre: "Nautilus Houseboat",
    fabricante: "Nautilus",
    modelo: "Houseboat 12",
    anio: 2023,
    tipo: "casa-flotante",
    descripcion:
      "Alojamiento amarrado en el pantalán, con dos habitaciones, cocina completa y terraza sobre el agua. No navega: es un apartamento con el mejor balcón del puerto.",
    esloraCm: 1_200,
    capacidad: 4,
    camarotes: 2,
    aseos: 1,
    potenciaCv: 0,
    precioBaseDia: 18_000,
    limpieza: 6_000,
    tasaPortuariaDia: 0,
    patronDia: null,
    fianza: 30_000,
    consumoLitrosHora: 0,
    descuentoSemana: 25,
    requiereTitulacion: false,
    minimoDias: 2,
    equipamiento: ["nevera", "cocina", "aire-acondicionado", "ducha-popa", "altavoz"],
    experiencias: [],
    puertos: ["santa-pola", "marina-denia", "altea", "moraira", "benidorm", "villajoyosa"],
  },
];

/**
 * Textos de opinión reales en tono y longitud. La semilla los reparte de
 * forma determinista para que dos ejecuciones den la misma base de datos.
 */
export const OPINIONES = [
  { autor: "Marta G.", nota: 5, texto: "El barco estaba impecable y la entrega fue puntualísima. Lo mejor: el precio que vimos al reservar fue exactamente el que pagamos, sin extras de última hora." },
  { autor: "Javier R.", nota: 5, texto: "Segunda vez que lo alquilamos. El propietario nos dio un par de calas que no salen en ninguna guía y acertó de pleno." },
  { autor: "Lucía M.", nota: 4, texto: "Muy bien en general. El motor tenía sus años pero funcionó sin problema todo el día. La nevera venía ya con hielo, detalle que se agradece." },
  { autor: "Andrés P.", nota: 5, texto: "Salimos siete y no fuimos apretados en ningún momento. La plataforma de baño es lo que marca la diferencia con otros barcos parecidos." },
  { autor: "Nuria B.", nota: 5, texto: "Primera vez que alquilábamos sin patrón y nos explicaron todo con calma antes de soltar amarras. Volveríamos sin dudarlo." },
  { autor: "Carlos V.", nota: 4, texto: "Buen barco y buen trato. La única pega es que el punto de recogida está algo lejos del aparcamiento, hay que cargar las cosas un buen rato." },
  { autor: "Elena S.", nota: 5, texto: "El desglose del precio con el combustible estimado nos ayudó a planificar la ruta. Al final gastamos menos de lo previsto y nos devolvieron la diferencia." },
  { autor: "Pau F.", nota: 5, texto: "Impecable. Fondeamos en tres calas y el barco se comportó de maravilla incluso cuando se levantó viento por la tarde." },
  { autor: "Rocío D.", nota: 4, texto: "Muy recomendable para familias. Los niños se pasaron el día tirándose desde la plataforma. El toldo da sombra de verdad, no como en otros." },
  { autor: "Ignacio L.", nota: 5, texto: "El patrón conocía cada rincón de la zona y nos llevó a un sitio donde estábamos solos. Hizo el día." },
  { autor: "Sara T.", nota: 5, texto: "Reservamos con dos días de antelación y todo salió perfecto. Comunicación rápida por el chat y cero sorpresas." },
  { autor: "Miguel Á.", nota: 4, texto: "Barco correcto y bien mantenido. Le falta un altavoz mejor, pero por lo demás nada que objetar." },
  { autor: "Cristina O.", nota: 5, texto: "Nos casamos el mes pasado y celebramos la despedida aquí. Cabíamos doce sin agobios y el patrón fue majísimo con el grupo." },
  { autor: "Diego H.", nota: 5, texto: "Salida de pesca redonda. Volvimos con dos bonitos y una lampuga. El equipo a bordo está en muy buen estado." },
  { autor: "Aitana C.", nota: 4, texto: "La puesta de sol desde el agua merece mucho la pena. Tres horas se hacen cortas pero es el formato perfecto para una primera vez." },
  { autor: "Guillem R.", nota: 5, texto: "Llevo años alquilando y es la primera vez que el precio de la web coincide con la factura. Solo por eso repetiré." },
] as const;
